/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  plugins: ["stylelint-selector-bem-pattern", "stylelint-order"],
  ignoreFiles: ["**/*.css"],
  rules: {
    "at-rule-empty-line-before": null,
    "block-no-empty": null,
    "declaration-empty-line-before": null,
    "property-no-vendor-prefix": null,
    "value-keyword-case": null,
    "scss/dollar-variable-empty-line-before": null,
    "scss/double-slash-comment-empty-line-before": null,
    "selector-class-pattern": null,
    "no-invalid-position-at-import-rule": null,
    "plugin/selector-bem-pattern": {
      preset: "bem",
    },
    "color-function-notation": [
      "modern",
      {
        ignore: ["with-var-inside"],
      },
    ],
    "scss/operator-no-newline-after": null,
    "order/order": ["dollar-variables", "custom-properties", "declarations"],
    "order/properties-order": [
      [
        {
          groupName: "all",
          emptyLineBefore: "always",
          properties: ["all"],
        },
        {
          groupName: "content",
          emptyLineBefore: "always",
          properties: ["content"],
        },
        {
          groupName: "dimensions",
          emptyLineBefore: "always",
          properties: [
            "min-width",
            "min-inline-size",
            "width",
            "inline-size",
            "max-width",
            "max-inline-size",
            "min-height",
            "min-block-size",
            "height",
            "block-size",
            "max-height",
            "max-block-size",
            "aspect-ratio",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "margin-block",
            "margin-block-end",
            "margin-block-start",
            "margin-inline",
            "margin-inline-end",
            "margin-inline-start",
            "margin-trim",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "padding-block",
            "padding-block-start",
            "padding-block-end",
            "padding-inline",
            "padding-inline-start",
            "padding-inline-end",
            "resize",
            "container",
            "container-name",
            "container-type",
          ],
        },
        {
          groupName: "grid placement",
          emptyLineBefore: "always",
          properties: [
            "grid-column-start",
            "grid-column-end",
            "grid-row-start",
            "grid-row-end",
            "grid-column",
            "grid-row",
            "grid-area",
            "justify-self",
            "align-self",
            "place-self",
          ],
        },
        {
          groupName: "grid and flex",
          emptyLineBefore: "always",
          properties: [
            "appearance",
            "display",
            "flex",
            "flex-grow",
            "flex-shrink",
            "flex-basis",
            "flex-wrap",
            "flex-direction",
            "grid",
            "grid-template",
            "grid-template-columns",
            "grid-template-rows",
            "grid-template-areas",
            "grid-auto-columns",
            "grid-auto-rows",
            "grid-auto-flow",
            "justify-items",
            "align-items",
            "place-items",
            "justify-content",
            "align-content",
            "place-content",
            "grid-column-gap",
            "grid-row-gap",
            "grid-gap",
            "gap",
            "box-sizing",
            "visibility",
            "overflow",
            "overflow-x",
            "overflow-y",
            "resize",
          ],
        },
        {
          groupName: "positioning",
          emptyLineBefore: "always",
          properties: [
            "position",
            "position-anchor",
            "position-area",
            "position-try",
            "position-try-fallbacks",
            "position-try-order",
            "position-visibility",
            "inset",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "anchor-name",
            "anchor-scope",
            "object-fit",
            "object-position",
            "object-view-box",
          ],
        },
        {
          groupName: "floating",
          emptyLineBefore: "always",
          properties: [
            "float",
            "clear",
            "break-before",
            "break-after",
            "break-inside",
          ],
        },
        {
          groupName: "typography",
          emptyLineBefore: "always",
          properties: [
            "color",
            "font",
            "font-family",
            "font-feature-settings",
            "font-kerning",
            "font-language-override",
            "font-palette",
            "font-size-adjust",
            "font-stretch",
            "font-synthesis",
            "font-synthesis-position",
            "font-synthesis-small-caps",
            "font-synthesis-style",
            "font-synthesis-weight",
            "font-variant",
            "font-variant-alternates",
            "font-variant-caps",
            "font-variant-east-asian",
            "font-variant-emoji",
            "font-variant-ligatures",
            "font-variant-numeric",
            "font-variant-position",
            "font-variation-settings",
            "font-width",
            "src",
            "font-size",
            "font-weight",
            "line-height",
            "text-align",
            "text-align-last",
            "vertical-align",
            "alignment-baseline",
            "baseline-shift",
            "baseline-source",
            "font-style",
            "font-display",
            "font-optical-sizing",
            "text-transform",
            "text-decoration",
            "text-decoration-thickness",
            "text-decoration-style",
            "text-decoration-color",
            "text-underline-position",
            "text-underline-offset",
            "direction",
            "letter-spacing",
            "word-spacing",
            "text-indent",
            "text-justify",
            "text-overflow",
            "text-overflow-ellipsis",
            "text-overflow-mode",
            "text-rendering",
            "text-size-adjust",
            "text-outline",
            "text-shadow",
            "text-transform",
            "text-wrap",
            "text-anchor",
            "text-combine-upright",
            "text-decoration-line",
            "text-decoration-skip-ink",
            "text-emphasis-color",
            "text-emphasis-position",
            "text-emphasis-style",
            "text-orientation",
            "text-wrap-mode",
            "text-wrap-style",
            "word-wrap",
            "word-break",
            "tab-size",
            "overflow-anchor",
            "overflow-block",
            "overflow-clip-margin",
            "overflow-inline",
            "overflow-wrap",
            "inset-block",
            "inset-block-end",
            "inset-block-start",
            "inset-inline",
            "inset-inline-end",
            "inset-inline-start",
            "text-emphasis",
            "white-space",
            "white-space-collapse",
            "word-spacing",
            "hyphens",
            "accent-color",
            "caret",
            "caret-color",
            "caret-shape",
            "writing-mode",
            "widows",
          ],
        },
        {
          groupName: "tables",
          emptyLineBefore: "always",
          properties: ["caption-side", "empty-cells", "table-layout"],
        },
        {
          groupName: "columns",
          emptyLineBefore: "always",
          properties: [
            "columns",
            "column-count",
            "column-fill",
            "column-gap",
            "column-rule",
            "column-rule-color",
            "column-rule-style",
            "column-rule-width",
            "column-span",
            "column-width",
          ],
        },
        {
          groupName: "list",
          emptyLineBefore: "always",
          properties: [
            "list-style",
            "list-style-type",
            "list-style-position",
            "list-style-image",
            "counter-increment",
            "counter-reset",
            "counter-set",
          ],
        },
        {
          groupName: "fill",
          emptyLineBefore: "always",
          properties: ["fill"],
        },
        {
          groupName: "background",
          emptyLineBefore: "always",
          properties: [
            "background",
            "background-color",
            "background-image",
            "background-size",
            "background-repeat",
            "background-clip",
            "background-attachment",
            "background-blend-mode",
            "background-origin",
            "background-position",
            "background-position-x",
            "background-position-y",
            "backdrop-filter",
          ],
        },
        {
          groupName: "border and outline",
          emptyLineBefore: "always",
          properties: [
            "border",
            "border-width",
            "border-color",
            "border-style",
            "border-top",
            "border-top-width",
            "border-top-color",
            "border-top-style",
            "border-right",
            "border-right-width",
            "border-right-color",
            "border-right-style",
            "border-bottom",
            "border-bottom-width",
            "border-bottom-color",
            "border-bottom-style",
            "border-left",
            "border-left-width",
            "border-left-color",
            "border-left-style",
            "border-spacing",
            "border-start-end-radius",
            "border-start-start-radius",
            "border-block",
            "border-block-color",
            "border-block-end",
            "border-block-end-color",
            "border-block-end-style",
            "border-block-end-width",
            "border-block-start",
            "border-block-start-color",
            "border-block-start-style",
            "border-block-start-width",
            "border-block-style",
            "border-block-width",
            "border-inline",
            "border-inline-color",
            "border-inline-end",
            "border-inline-end-color",
            "border-inline-end-style",
            "border-inline-end-width",
            "border-inline-start",
            "border-inline-start-color",
            "border-inline-start-style",
            "border-inline-start-width",
            "border-inline-style",
            "border-inline-width",
            "border-radius",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
            "border-end-end-radius",
            "border-end-start-radius",
            "border-collapse",
            "border-image",
            "border-image-outset",
            "border-image-repeat",
            "border-image-slice",
            "border-image-source",
            "border-image-width",
            "outline",
            "outline-width",
            "outline-color",
            "outline-style",
            "outline-offset",
          ],
        },
        {
          groupName: "effects",
          emptyLineBefore: "always",
          properties: [
            "box-shadow",
            "opacity",
            "filter",
            "mask",
            "mask-border",
            "mask-border-mode",
            "mask-border-outset",
            "mask-border-repeat",
            "mask-border-slice",
            "mask-border-source",
            "mask-border-width",
            "mask-clip",
            "mask-composite",
            "mask-image",
            "mask-mode",
            "mask-origin",
            "mask-position",
            "mask-repeat",
            "mask-size",
            "mask-type",
          ],
        },
        {
          groupName: "transform",
          emptyLineBefore: "always",
          properties: [
            "transform",
            "transform-box",
            "transform-origin",
            "transform-style",
            "perspective",
            "perspective-origin",
            "backface-visibility",
            "translate",
          ],
        },
        {
          groupName: "animation",
          emptyLineBefore: "always",
          properties: [
            "transition",
            "transition-behavior",
            "transition-delay",
            "transition-duration",
            "transition-property",
            "transition-timing-function",
            "animation",
            "animation-name",
            "animation-duration",
            "animation-timing-function",
            "animation-delay",
            "animation-iteration-count",
            "animation-direction",
            "animation-fill-mode",
            "animation-play-state",
            "animation-composition",
            "animation-range",
            "animation-range-end",
            "animation-range-start",
            "animation-timeline",
            "view-timeline",
            "view-timeline-axis",
            "view-timeline-inset",
            "view-timeline-name",
            "view-transition-class",
            "view-transition-name",
          ],
        },
        {
          groupName: "misc",
          emptyLineBefore: "always",
          properties: [
            "scroll-behavior",
            "scroll-margin",
            "scroll-margin-block",
            "scroll-margin-block-end",
            "scroll-margin-block-start",
            "scroll-margin-bottom",
            "scroll-margin-inline",
            "scroll-margin-inline-end",
            "scroll-margin-inline-start",
            "scroll-margin-left",
            "scroll-margin-right",
            "scroll-margin-top",
            "scroll-marker-group",
            "scroll-padding",
            "scroll-padding-block",
            "scroll-padding-block-end",
            "scroll-padding-block-start",
            "scroll-padding-bottom",
            "scroll-padding-inline",
            "scroll-padding-inline-end",
            "scroll-padding-inline-start",
            "scroll-padding-left",
            "scroll-padding-right",
            "scroll-padding-top",
            "scroll-snap-align",
            "scroll-snap-stop",
            "scroll-snap-type",
            "scroll-timeline",
            "scroll-timeline-axis",
            "scroll-timeline-name",
            "scrollbar-color",
            "scrollbar-gutter",
            "scrollbar-width",
            "overscroll-behavior",
            "overscroll-behavior-block",
            "overscroll-behavior-inline",
            "overscroll-behavior-x",
            "overscroll-behavior-y",
          ],
        },
        {
          groupName: "misc",
          emptyLineBefore: "always",
          properties: [
            "cursor",
            "clip",
            "clip-path",
            "clip-rule",
            "zoom",
            "box-decoration-break",
            "color-interpolation",
            "color-interpolation-filters",
            "color-scheme",
            "contain",
            "contain-intrinsic-block-size",
            "contain-intrinsic-height",
            "contain-intrinsic-inline-size",
            "contain-intrinsic-size",
            "contain-intrinsic-width",
            "content-visibility",
            "cx",
            "cy",
            "d",
            "dominant-baseline",
            "dynamic-range-limit",
            "field-sizing",
            "fill-opacity",
            "fill-rule",
            "flex-flow",
            "flood-color",
            "flood-opacity",
            "forced-color-adjust",
            "hanging-punctuation",
            "hyphenate-character",
            "hyphenate-limit-chars",
            "image-orientation",
            "image-rendering",
            "initial-letter",
            "interpolate-size",
            "isolation",
            "lighting-color",
            "line-break",
            "line-clamp",
            "marker",
            "marker-end",
            "marker-mid",
            "marker-start",
            "math-depth",
            "math-style",
            "mix-blend-mode",
            "offset",
            "offset-anchor",
            "offset-distance",
            "offset-path",
            "offset-position",
            "offset-rotate",
            "order",
            "orphans",
            "overlay",
            "page",
            "paint-order",
            "pointer-events",
            "print-color-adjust",
            "quotes",
            "r",
            "reading-flow",
            "reading-order",
            "rotate",
            "row-gap",
            "ruby-align",
            "ruby-overhang",
            "ruby-position",
            "rx",
            "ry",
            "scale",
            "shape-image-threshold",
            "shape-margin",
            "shape-outside",
            "shape-rendering",
            "stop-color",
            "stop-opacity",
            "stroke",
            "stroke-dasharray",
            "stroke-dashoffset",
            "stroke-linecap",
            "stroke-linejoin",
            "stroke-miterlimit",
            "stroke-opacity",
            "stroke-width",
            "timeline-scope",
            "touch-action",
            "unicode-bidi",
            "user-select",
            "vector-effect",
            "will-change",
            "x",
            "y",
          ],
        },
      ],
      {
        unspecified: "bottomAlphabetical",
        emptyLineBeforeUnspecified: "always",
      },
    ],
  },
};
